// pages/_app.js
import React from "react";
import { Inter } from "next/font/google";
import Footer from "./components/footer/Footer";
import '../app/globals.css'
import NavigationBar from "./components/navbar/NavigationBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
       <NavigationBar/>
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
